# Generated by Django 2.2.22 on 2021-05-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coral',
            name='image_path',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
