# Generated by Django 2.2.22 on 2021-05-26 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coral_genus', models.CharField(max_length=255)),
                ('coral_family', models.CharField(max_length=255)),
                ('discoverer', models.CharField(max_length=255)),
                ('year_discovered', models.IntegerField()),
                ('characteristic', models.CharField(max_length=1024)),
                ('kind_of_look_alike', models.CharField(max_length=1024)),
                ('distribution', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('corals', models.ManyToManyField(to='core.Coral')),
            ],
        ),
        migrations.AddField(
            model_name='coral',
            name='coral_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Species'),
        ),
    ]
